export const PILAR_DE_CONTENIDO = [
  'UX-UI',
  'Base de datos',
  'Expresiones y fórmulas',
  'Automatización',
  'Flujos de trabajo',
  'Acciones-Behavior',
  'Seguridad-Accesibilidad',
  'General',
] as const;

export const SECTOR = [
  'Industria',
  'Gestión del tiempo',
  'Gestión de proyectos',
  'Gestión de inventarios',
  'Ventas y CRM',
  'Obras y construcción',
  'Logística y transporte',
  'Servicios profesionales',
  'Marketing digital',
  'E-Commerce',
  'Entretenimiento y medios',
  'Seguridad y vigilancia',
  'Investigación y desarrollo',
  'Agricultura y medio ambiente',
  'Administración',
] as const;

export const FUNCIONALIDADES = [
  'Calendario',
  'Generación de PDF',
  'Reportes automáticos',
  'Chatbot (BOT)',
  'Emails',
  'SMS',
  'Notificaciones Push',
  'Generación y Escaneo QR',
  'Geolocalización',
  'OCR',
  'Machine Learning',
  'Estadísticas de uso',
  'Dashboard - Reportes y análisis',
  'Gestión de Usuarios',
  'Reporting avanzado',
  'Integración de datos',
  'Gestión de permisos',
  'Análisis de datos',
  'Optimización - Performance',
  'Despliegue-Deploy',
  'Importación - Exportación de datos',
  'Firmas digitales',
  'Escaneo de documentos',
  'Monitor de automatizaciones',
  'Historial de auditoría',
  'API - Integraciones',
] as const;

export const HERRAMIENTAS_Y_PLATAFORMAS = [
  'Google Sheets',
  'Looker Studio',
  'MySQL',
  'PostgreSQL',
  'Salesforce',
  'Airtable',
  'Dropbox',
  'Box',
  'Google Analytics',
  'Zapier',
  'WordPress',
  'Shopify',
  'WhatsApp API',
  'Power BI',
  'Twilio',
  'Trello',
  'Google Calendar',
  'Google Drive',
  'Google Maps',
] as const;

export const LENGUAJES = ['español', 'ingles'] as const;

export const PLATAFORMA = ['AppSheet', 'Powerapps'] as const;
